<a href="https://colab.research.google.com/github/PranavShashidhara/World-Bank-Project/blob/main/Dimension_Tables_setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data_df = pd.read_parquet('WORLD_BANK_GDP_DEBT_DATA.parquet')

In [ ]:
defaulted_countries = pd.read_csv('Debt_failed_countries.csv')

In [ ]:
data_df.head()

,Country,Year,CURRENT_GDP_USD,GDP_GROWTH_PCT,ANUAL_INFLATION_PCT,TOT_EXT_DEBT_USD,TOT_GOVT_DEBT_LCU,LONG_EXT_DEBT_USD,PUBLIC_OWNED_DEBT_USD,PRIVATE_OWNED_DEBT_USD,...,CUR_VAL_EXT_DEBT,EXPORTS,IMPORTS,TAX_REVENUE_PCT_GDP,UNEMPLOYMENT_RATE,POP_GROWTH_RATE,DEBT_TO_GDP,TRADE_BALANCE,TRADE_BAL_PCT_GDP,REAL_GDP_GROWTH
0,Zimbabwe,1960,1.052990e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zambia,1960,7.130000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Yemen, Rep.",1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,West Bank and Gaza,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Virgin Islands (U.S.),1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
len(data_df['Country'].unique().tolist())

266

In [ ]:
import requests
import json
url = "https://api.worldbank.org/v2/country?format=json&per_page=300"
response = requests.get(url)
if response.status_code == 200:
  data = response.json()
  world_bank_countries = pd.DataFrame(pd.json_normalize(data[1]))
else:
  print("Failed to make a connection", response.status_code)
world_bank_countries

,id,iso2Code,name,capitalCity,longitude,latitude,region.id,region.iso2code,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,ABW,AW,Aruba,Oranjestad,-70.0167,12.5167,LCN,ZJ,Latin America & Caribbean,,,,HIC,XD,High income,LNX,XX,Not classified
1,AFE,ZH,Africa Eastern and Southern,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,SAS,8S,South Asia,SAS,8S,South Asia,LIC,XM,Low income,IDX,XI,IDA
3,AFR,A9,Africa,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,AFW,ZI,Africa Western and Central,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
292,YEM,YE,"Yemen, Rep.",Sana'a,44.2075,15.352,MEA,ZQ,Middle East & North Africa,MNA,XQ,Middle East & North Africa (excluding high inc...,LIC,XM,Low income,IDX,XI,IDA
293,ZAF,ZA,South Africa,Pretoria,28.1871,-25.746,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),UMC,XT,Upper middle income,IBD,XF,IBRD
294,ZMB,ZM,Zambia,Lusaka,28.2937,-15.3982,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDX,XI,IDA
295,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend

In [ ]:
data_df['Country']

0                              Zimbabwe
1                                Zambia
2                           Yemen, Rep.
3                    West Bank and Gaza
4                 Virgin Islands (U.S.)
                      ...
16753    Central Europe and the Baltics
16754            Caribbean small states
16755                        Arab World
16756        Africa Western and Central
16757       Africa Eastern and Southern
Name: Country, Length: 16758, dtype: object

In [ ]:
import pandas as pd
import numpy as np

date_range = pd.date_range(start="2002-01-01", end="2100-01-01", freq="D")
time_dimension_df = pd.DataFrame(date_range, columns=["FullDate"])

time_dimension_df['DateKey'] = time_dimension_df["FullDate"].dt.strftime("%Y%m%d").astype(int)
time_dimension_df['Year'] = time_dimension_df['FullDate'].dt.year
time_dimension_df['Quarter'] = time_dimension_df['FullDate'].dt.quarter
time_dimension_df['Month'] = time_dimension_df['FullDate'].dt.month
time_dimension_df['Day'] = time_dimension_df['FullDate'].dt.day
time_dimension_df['DayOfWeek'] = time_dimension_df['FullDate'].dt.dayofweek + 1
time_dimension_df['WeekOfYear'] = time_dimension_df['FullDate'].dt.isocalendar().week
time_dimension_df['IsWeekend'] = time_dimension_df['DayOfWeek'].isin([6,7])

time_dimension_df['MonthName'] = time_dimension_df['FullDate'].dt.strftime("%B")
time_dimension_df['QuarterName'] = "Q" + time_dimension_df['Quarter'].astype(str)
time_dimension_df['DayName'] = time_dimension_df['FullDate'].dt.strftime('%A')
time_dimension_df

,FullDate,DateKey,Year,Quarter,Month,Day,DayOfWeek,WeekOfYear,IsWeekend,MonthName,QuarterName,DayName
0,2002-01-01,20020101,2002,1,1,1,2,1,False,January,Q1,Tuesday
1,2002-01-02,20020102,2002,1,1,2,3,1,False,January,Q1,Wednesday
2,2002-01-03,20020103,2002,1,1,3,4,1,False,January,Q1,Thursday
3,2002-01-04,20020104,2002,1,1,4,5,1,False,January,Q1,Friday
4,2002-01-05,20020105,2002,1,1,5,6,1,True,January,Q1,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...
35790,2099-12-28,20991228,2099,4,12,28,1,53,False,December,Q4,Monday
35791,2099-12-29,20991229,2099,4,12,29,2,53,False,December,Q4,Tuesday
35792,2099-12-30,20991230,2099,4,12,30,3,53,False,December,Q4,Wednesday
35793,2099-12-31,20991231,2099,4,12,31,4,53,False,December,Q4,Thursday
35794,2100-01-01,21000101,2100,1,1,1,5,53,False,January,Q1,Friday

In [ ]:
import wbgapi as wb
df = wb.data.DataFrame("IC.BUS.EASE.XQ")
df.notnull()

,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,YR1969,...,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021,YR2022,YR2023
economy,,,,,,,,,,,,,,,,,,,,,
ABW,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
AFE,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
AFG,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
AFW,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
AGO,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XKX,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
YEM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
ZAF,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
ZMB,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
ZWE,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [ ]:
def default_indicator(row):
    if row['DEBT_TO_GDP'] > 100 and row['ANNUAL_INFLATION_PCT'] > 10:
        return 1
    elif row['TOT_EXT_DEBT_USD'] > row['EXPORTS'] * 5:
        return 1
    return 0

# Apply the function to each row of the dataframe
data_df['DEBT_TO_GDP'] = data_df['DEBT_TO_GDP'].fillna(0)
data_df['ANNUAL_INFLATION_PCT'] = data_df['ANUAL_INFLATION_PCT'].fillna(0)
data_df['DEFAULT'] = data_df.apply(default_indicator, axis=1)
data_df.fillna(0, inplace=True)

data_df[data_df['DEFAULT']==1].sort_values('Country').groupby(['Country', 'Year']).head()

,Country,Year,CURRENT_GDP_USD,GDP_GROWTH_PCT,ANUAL_INFLATION_PCT,TOT_EXT_DEBT_USD,TOT_GOVT_DEBT_LCU,LONG_EXT_DEBT_USD,PUBLIC_OWNED_DEBT_USD,PRIVATE_OWNED_DEBT_USD,...,IMPORTS,TAX_REVENUE_PCT_GDP,UNEMPLOYMENT_RATE,POP_GROWTH_RATE,DEBT_TO_GDP,TRADE_BALANCE,TRADE_BAL_PCT_GDP,REAL_GDP_GROWTH,ANNUAL_INFLATION_PCT,DEFAULT
8727,Albania,1992,6.521750e+08,-7.187111,16.673716,6.326218e+08,0.000000e+00,1.268538e+08,1.268538e+08,0.000000e+00,...,6.279524e+08,0.000000,30.007,-0.606435,0.970018,-5.464332e+08,7.602961e+07,-23.860827,16.673716,1
8461,Albania,1991,1.099559e+09,-28.002142,5.114552,5.114858e+08,0.000000e+00,8.620013e+07,8.620013e+07,0.000000e+00,...,3.143167e+08,0.000000,10.304,-0.602810,0.465174,-2.320167e+08,8.285676e+06,-33.116693,5.114552,1
10583,Argentina,1999,2.835230e+11,-3.385457,0.000000,1.519138e+11,0.000000e+00,1.175837e+11,9.026421e+10,2.731946e+10,...,3.276270e+10,0.000000,14.050,1.152044,0.535808,-4.900400e+09,1.447486e+09,0.000000,0.000000,1
6593,Argentina,1984,1.129886e+11,1.570739,0.000000,4.906081e+10,0.000000e+00,3.724414e+10,2.690414e+10,1.034000e+10,...,5.374286e+09,0.000000,0.000,1.537153,0.434210,3.201429e+09,2.038167e+09,0.000000,0.000000,1
7923,Argentina,1989,7.662966e+10,-7.156950,0.000000,6.553841e+10,0.000000e+00,5.391388e+10,5.211388e+10,1.800000e+09,...,5.041763e+09,0.000000,0.000,1.487655,0.855262,4.964851e+09,-6.937105e+08,0.000000,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9311,Zambia,1995,3.806983e+09,2.897669,6.730886,6.957808e+09,5.108200e+09,5.304218e+09,5.290764e+09,1.345400e+07,...,1.382915e+09,15.689500,16.825,2.446966,1.827643,-1.303786e+08,-4.499430e+07,-3.833217,6.730886,1
10641,Zambia,2000,3.600632e+09,3.897323,23.828288,5.811480e+09,0.000000e+00,4.508222e+09,4.443650e+09,6.457200e+07,...,1.312920e+09,0.000000,12.930,2.766606,1.614017,-4.515102e+08,-1.158514e+08,-19.930965,23.828288,1
10907,Zambia,2001,4.094441e+09,5.316868,28.926060,6.189777e+09,0.000000e+00,4.980703e+09,4.826636e+09,1.540670e+08,...,1.619703e+09,16.540704,13.410,2.996056,1.511751,-5.916011e+08,-1.112687e+08,-23.609192,28.926060,1
10375,Zambia,1999,3.404285e+09,4.650190,18.906776,5.953050e+09,0.000000e+00,4.578199e+09,4.505436e+09,7.276300e+07,...,1.182319e+09,16.954308,12.496,2.620055,1.748693,-3.299806e+08,-7.096067e+07,-14.256586,18.906776,1
9045,Zambia,1994,3.656806e+09,-8.625442,4.988443,6.808521e+09,3.652300e+09,5.193917e+09,5.180463e+09,1.345400e+07,...,1.232351e+09,17.236518,18.645,2.428276,1.861876,-2.741888e+07,3.178837e+06,-13.613885,4.988443,1

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(data_df[['Country']])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(['Country']))
pd.concat([data_df.drop('Country', axis=1), one_hot_df], axis=1)

,Year,CURRENT_GDP_USD,GDP_GROWTH_PCT,ANUAL_INFLATION_PCT,TOT_EXT_DEBT_USD,TOT_GOVT_DEBT_LCU,LONG_EXT_DEBT_USD,PUBLIC_OWNED_DEBT_USD,PRIVATE_OWNED_DEBT_USD,SHORT_TERM_EXT_DEBT,...,Country_Uzbekistan,Country_Vanuatu,"Country_Venezuela, RB",Country_Viet Nam,Country_Virgin Islands (U.S.),Country_West Bank and Gaza,Country_World,"Country_Yemen, Rep.",Country_Zambia,Country_Zimbabwe
0,1960,1.052990e+09,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1960,7.130000e+08,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1960,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1960,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1960,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16753,2022,1.943576e+12,4.247073,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16754,2022,4.813805e+10,22.478217,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16755,2022,3.613682e+12,5.793109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16756,2022,8.771408e+11,3.784486,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16757,2022,1.183962e+12,3.554422,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
def expand_years(country, year_range):
    year_range = year_range.replace("–", "-")
    if "-" in year_range:
        start, end = year_range.split("-")
        start = int(start)
        end = int(end[:-1] + "9") if "s" in end else int(end)
    else:
        start = end = int(year_range)
    return [(country, year) for year in range(start, end + 1)]

expanded_data = []
for row in defaulted_countries.itertuples(index=False):
    country = row.Country
    year_range = row.Date
    expanded_data.extend(expand_years(country, year_range))

expanded_default = pd.DataFrame(expanded_data, columns=['Country', 'Year'])

defaulted_countries=expanded_default

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score


X = data_df[['CURRENT_GDP_USD', 'GDP_GROWTH_PCT', 'ANNUAL_INFLATION_PCT', 'TOT_EXT_DEBT_USD', 'DEBT_TO_GDP', 'TRADE_BALANCE', 'UNEMPLOYMENT_RATE', 'POP_GROWTH_RATE']]
y = data_df['DEFAULT']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled.shape)
print(y_train.shape)

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

(13406, 8)
(13406,)
Accuracy: 0.9767303102625299
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3273
           1       0.53      0.10      0.17        79

    accuracy                           0.98      3352
   macro avg       0.76      0.55      0.58      3352
weighted avg       0.97      0.98      0.97      3352

In [ ]:
defaulted_countries['Country'] = defaulted_countries['Country'].str.split('\xa0', expand=True)[1]
default=defaulted_countries[defaulted_countries['Year']>=1960]
data_df.loc[:, 'Year'] = data_df['Year'].astype(int)
defaulted_countries.loc[:, 'Year'] = defaulted_countries['Year'].astype(int)

In [ ]:
len(defaulted_countries['Country'].unique())

90

In [ ]:
data_df[pd.merge(data_df, defaulted_countries, on =['Country', 'Year'], how = 'left')['DEFAULT']==1]['Country'].unique()

array(['Mali', 'Pakistan', 'Turkiye', 'Sudan', 'Somalia', 'Ghana',
       'Guinea-Bissau', 'Bangladesh', 'Uganda', 'Sierra Leone',
       'Madagascar', 'Guyana', 'Comoros', 'Benin', 'Lao PDR', 'Argentina',
       'Egypt, Arab Rep.', 'Bolivia', 'Burundi', 'Peru', 'Nicaragua',
       'Viet Nam', 'Tanzania', "Cote d'Ivoire", 'Rwanda', 'Mozambique',
       'Albania', 'Zambia', 'Niger', 'Haiti', 'Congo, Rep.',
       'Congo, Dem. Rep.', 'Serbia', 'Mauritania', 'Burkina Faso',
       'Eritrea', 'Central African Republic', 'Lebanon', 'Chad',
       'Tajikistan', 'Panama', 'Montenegro', 'Gambia, The', 'Vanuatu',
       'Samoa'], dtype=object)

In [ ]:
defaulted_countries

             Country  Year
0            Algeria  1991
1             Angola  1976
2             Angola  1985
3             Angola  1992
4             Angola  1993
..               ...   ...
378  Solomon Islands  2000
379  Solomon Islands  2001
380  Solomon Islands  2002
381  Solomon Islands  2003
382  Solomon Islands  2004

[383 rows x 2 columns]